publications_bootstrap/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

app_name = 'publications_bootstrap'
urlpatterns = [
    url(r'^$', views.by_year, name='index'),
    url(r'^(?P<publication_id>\d+)/$', views.by_id, name='id'),
    url(r'^year/(?P<year>\d+)/$', views.by_year, name='year'),
    url(r'^tag/(?P<tag>.+)/$', views.by_tag, name='tag'),
    url(r'^catalog/(?P<title>.+)/$', views.for_catalog, name='catalog'),
    url(r'^unapi/$', views.by_unapi, name='unapi'),
    url(r'^(?P<name>.+)/$', views.by_author, name='author'),
]

publications_bootstrap/models/publication.py
# -*- coding: utf-8 -*-
import warnings
from string import ascii_uppercase

from django.conf import settings
from django.db import models
from django.utils.http import urlquote_plus
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField
from echoices.enums import EChoice, EOrderedChoice
from echoices.fields import make_echoicefield

from ..fields import NullCharField, PagesField
from ..models import Type

if 'django.contrib.sites' in settings.INSTALLED_APPS:
    from django.contrib.sites.models import Site


class Publication(models.Model):
    """
    Model representing a publication.
    """

    class Meta:
        ordering = ['-year', '-month', '-id']
        app_label = 'publications_bootstrap'  # Fix for Django<1.7

    # names shown in admin area
    class EMonths(EOrderedChoice):
        JAN = (1, _('January'), 'Jan')
        FEB = (2, _('February'), 'Feb')
        MAR = (3, _('March'), 'Mar')
        APR = (4, _('April'), 'Apr')
        MAY = (5, _('May'), 'May')
        JNE = (6, _('June'), 'Jun')
        JLY = (7, _('July'), 'Jul')
        AUG = (8, _('August'), 'Aug')
        SEP = (9, _('September'), 'Sep')
        OCT = (10, _('October'), 'Oct')
        NOV = (11, _('November'), 'Nov')
        DEC = (12, _('December'), 'Dec')

        def __init__(self, v_, l_, bibtex):
            # abbreviations used in BibTex
            self.bibtex = bibtex

    # Status of the publication
    class EStatuses(EChoice):
        DRAFT = ('d', _('draft'))
        SUBMITTED = ('s', _('submitted'))
        ACCEPTED = ('a', _('accepted'))
        PUBLISHED = ('p', _('published'))

    type = models.ForeignKey(Type, db_index=True)
    citekey = NullCharField(max_length=512, blank=True, null=True, unique=True, db_index=True,
                            help_text='BibTex citation key. Leave blank if unsure.')
    title = models.CharField(max_length=512, db_index=True)
    authors = models.CharField(max_length=2048,
                               help_text='List of authors separated by commas or <i>and</i>.')
    year = models.PositiveIntegerField(db_index=True)
    month = make_echoicefield(EMonths, blank=True, null=True, db_index=True)
    journal = models.CharField(max_length=256, blank=True)
    book_title = models.CharField(max_length=256, blank=True,
                                  help_text='Title of a book, part of which is being cited. See '
                                            'the LATEX book for how to type titles. For book '
                                            'entries, use the `title` field instead')
    publisher = models.CharField(max_length=256, blank=True)
    editor = models.CharField(max_length=256, blank=True,
                              help_text='Name(s) of editor(s), typed as indicated in the LATEX '
                                        'book. If there is also an `author` field, then the '
                                        '`editor` field gives the editor of the book or '
                                        'collection in which the reference appears.')
    edition = models.CharField(max_length=256, blank=True,
                               help_text='The edition of a book -- for example, "Second". This '
                                         'should be an ordinal, and should have the first letter '
                                         'capitalized.')
    institution = models.CharField(max_length=256, blank=True)
    school = models.CharField(max_length=256, blank=True,
                              help_text='The name of the school where a thesis was written.')
    organization = models.CharField(max_length=256, blank=True,
                                    help_text='The organization that sponsors a conference or '
                                              'that publishes a manual.')
    location = models.CharField(max_length=256, blank=True,
                                help_text="Place of publication, location of conference, "
                                          "or publisher's address.")
    country = CountryField(blank=True)
    series = models.CharField(blank=True, max_length=256,
                              help_text='The name of a series or set of books. When citing an '
                                        'entire book, the `title` field gives its title and an '
                                        'optional `series` field gives the name of a series or '
                                        'multi-volume set in which the book is published.')
    volume = models.CharField(blank=True, null=True, max_length=128)
    number = models.CharField(blank=True, null=True, max_length=128, verbose_name='Issue number',
                              help_text='The number of a journal, magazine, technical report, or '
                                        'of a work in a series. An issue of a journal or magazine '
                                        'is usually identified by its volume and number; the '
                                        'organization that issues a technical report usually '
                                        'gives it a number; and sometimes books are given numbers '
                                        'in a named series.')
    chapter = models.CharField(blank=True, null=True, max_length=128)
    section = models.CharField(blank=True, null=True, max_length=128)  # Not officially
    # recognized as Bibtex Field Type
    pages = PagesField(max_length=32, blank=True)
    note = models.CharField(max_length=256, blank=True,
                            help_text='Any additional information that can help the reader. The '
                                      'first word should be capitalized.')
    tags = models.CharField(max_length=256, blank=True,
                            help_text='List of tags separated by commas.')
    url = models.URLField(blank=True, verbose_name='URL', help_text='Link to PDF or journal page.')
    code = models.URLField(blank=True, help_text='Link to page with code.')
    pdf = models.FileField(upload_to='publications_bootstrap/', verbose_name='PDF', blank=True, null=True)
    image = models.ImageField(upload_to='publications_bootstrap/images/', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='publications_bootstrap/thumbnails/', blank=True, null=True)
    external = models.BooleanField(default=False, db_index=True,
                                   help_text='If publication was written in another lab, mark as external.')
    abstract = models.TextField(blank=True)
    doi = NullCharField(max_length=128, verbose_name='DOI', blank=True, null=True, unique=True)
    isbn = NullCharField(max_length=32, verbose_name='ISBN', blank=True, null=True, unique=True,
                         help_text='Only for a book.')  # A-B-C-D
    status = make_echoicefield(EStatuses, default=EStatuses.PUBLISHED, blank=False)

    def __init__(self, *args, **kwargs):
        models.Model.__init__(self, *args, **kwargs)

        # post-process tags
        self.tags = self.tags.replace(';', ',')
        self.tags = self.tags.replace(', and ', ', ')
        self.tags = self.tags.replace(',and ', ', ')
        self.tags = self.tags.replace(' and ', ', ')
        self.tags = [s.strip().lower() for s in self.tags.split(',')]
        self.tags = ', '.join(self.tags).lower()

        self._produce_author_lists()

    def _produce_author_lists(self):
        """
        Parse authors string to create lists of authors.
        """

        # post-process author names
        self.authors = self.authors.replace(', and ', ', ')
        self.authors = self.authors.replace(',and ', ', ')
        self.authors = self.authors.replace(' and ', ', ')
        self.authors = self.authors.replace(';', ',')

        # list of authors
        self.authors_list = [author.strip() for author in self.authors.split(',')]

        # simplified representation of author names
        self.authors_list_simple = []

        # author names represented as a tuple of given and family name
        self.authors_list_split = []

        # tests if title already ends with a punctuation mark
        self.title_ends_with_punct = self.title[-1] in ['.', '!', '?'] if len(self.title) > 0 else False

        suffixes = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', "Jr.", "Sr."]
        prefixes = ['Dr.']
        prepositions = ['van', 'von', 'der', 'de', 'den']

        # further post-process author names
        for i, author in enumerate(self.authors_list):
            if author == '':
                continue

            names = author.split(' ')

            # check if last string contains initials
            if (len(names[-1]) <= 3) \
                    and names[-1] not in suffixes \
                    and all(c in ascii_uppercase for c in names[-1]):
                # turn "Gauss CF" into "C. F. Gauss"
                names = [c + '.' for c in names[-1]] + names[:-1]

            # number of suffixes
            num_suffixes = 0
            for name in names[::-1]:
                if name in suffixes:
                    num_suffixes += 1
                else:
                    break

            # abbreviate names
            for j, name in enumerate(names[:-1 - num_suffixes]):
                # don't try to abbreviate these
                if j == 0 and name in prefixes:
                    continue
                if j > 0 and name in prepositions:
                    continue

                if (len(name) > 2) or (len(name) and (name[-1] != '.')):
                    k = name.find('-')
                    if 0 < k + 1 < len(name):
                        # take care of dash
                        names[j] = name[0] + '.-' + name[k + 1] + '.'
                    else:
                        names[j] = name[0] + '.'

            if len(names):
                self.authors_list[i] = ' '.join(names)

publications_bootstrap/templates/publications_bootstrap/components/download_all.html
<section class="download_all">
    <div class="input-group">
        <span class="input-group-addon" id="basic-addon">Export all as</span>
        <div class="input-group-btn">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                Citation format
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="?plain">Plain text</a>
                <a class="dropdown-item" href="?ris">RIS</a>
                <a class="dropdown-item" href="?bibtex">BibTex</a>
            </div>
        </div>
    </div>
</section>

publications_bootstrap/templates/publications_bootstrap/components/empty.html
<div class="alert alert-{% if error %}danger{% else %}info{% endif %}" role="alert">
    <h4 class="alert-heading">{{ alert.heading|default:"Sorry" }}</h4>
    <p>{{ alert.message|default:"There are no publications." }}</p>
</div>

publications_bootstrap/templates/publications_bootstrap/components/publication.html
{% load publication_extras %}

<div class="card">
    <div class="card-body">
        <p class="card-text">
            {{ publication.authors_escaped|flatten_authors:"limit=6&last=, and" }}
        </p>
    </div>
    <h3 class="card-header">
        <a href="{% url 'publications_bootstrap:id' publication.pk %}"
           class="title">{{ publication.title|tex_parse }}</a>
    </h3>
    <div class="card-body">
        <p class="card-text">
            {% if publication.journal %}
                <i>{{ publication.journal }}{% if publication.note %} ({{ publication.note }}
                    ){% endif %},
                    {% if publication.volume %}<b>{{ publication.volume }}</b>
                        {% if publication.number %}({{ publication.number }})
                        {% endif %},{% endif %}
                    {% if publication.pages %}{{ publication.pages }},{% endif %}
                    {{ publication.year }}
                </i>
            {% else %}
                <i>{% if publication.book_title %}{{ publication.book_title }}
                    {% if publication.note %} ({{ publication.note }})
                    {% endif %},{% endif %}
                    {% if publication.publisher %}{{ publication.publisher }},{% endif %}
                    {% if publication.institution %}{{ publication.institution }},{% endif %}
                    {{ publication.year }}{% if publication.isbn %},
                        ISBN {{ publication.isbn }}{% endif %}</i>
            {% endif %}
        </p>
        {% if publication.abstract %}
            <p class="card-text">
                {{ publication.abstract|tex_parse }}
            </p>
        {% endif %}
    </div>
    {% if publication.tags %}
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                {% for tag, tag_escaped in publication.tags_escaped %}
                    <a class="tag"
                       href="{% url 'publications_bootstrap:tag' tag_escaped %}"><span
                            class="tag tag-default">{{ tag }}</span></a>
                {% endfor %}
            </li>
        </ul>
    {% endif %}
    <div class="card-body">
        <div class="row">
            <div class="col-xs-5">
                <form class="form-inline">
                    {% if publication.doi %}
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">DOI</span>
                                <input title="DOI number" type="text" class="form-control"
                                       value="{{ publication.doi }}"
                                       aria-describedby="basic-addon1" readonly>
                            </div>
                            <a class="btn btn-primary" rel="external"
                               href="http://dx.doi.org/{{ publication.doi }}"><img
                                    src="https://maxcdn.icons8.com/Color/PNG/24/Programming/external_link-24.png"
                                    title="External link to DOI" height="12"></a>
                        </div>
                    {% endif %}
                    {% if publication.isbn %}
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">ISBN</span>
                                <input title="ISBN number" type="text" class="form-control"
                                       value="{{ publication.isbn }}"
                                       aria-describedby="basic-addon2" readonly>
                            </div>
                            <a class="btn btn-primary" rel="external"
                               href="http://isbndb.com/search/all?query=978-1-60558-139-2"><img
                                    src="https://maxcdn.icons8.com/Color/PNG/24/Programming/external_link-24.png"
                                    title="External link to ISBN" height="12"></a>
                        </div>
                    {% endif %}
                </form>
            </div>
            <div class="col-xs-3">
                <div class="btn-group" role="group" aria-label="Button group">
                    {% if publication.code %}
                        <a class="btn btn-secondary" href="{{ publication.code }}">Code</a>
                    {% endif %}
                    {% if publication.url %}
                        <a class="btn btn-secondary" rel="external" href="{{ publication.url }}">URL</a>
                    {% endif %}
                </div>
                {% if publication.links %}
                    <div class="btn-group" role="group">
                        <button class="btn btn-secondary dropdown-toggle" type="button"
                                id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Additional links
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            {% for link in publication.links %}
                                <a class="dropdown-item" rel="external"
                                   href="{{ link.url }}">{{ link.description }}</a>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="col-xs-4">
                {% if publication.pdf or publication.files %}
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon">Download</span>
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-secondary dropdown-toggle"
                                    data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                File
                            </button>
                            <div class="dropdown-menu">
                                {% if publication.pdf %}
                                    <a class="dropdown-item" href="{{ publication.pdf.url }}">
                                        <img src="https://maxcdn.icons8.com/Color/PNG/48/Files/pdf_2-48.png"
                                             title="PDF 2" height="48">Publication as PDF</a>
                                {% endif %}
                                {% for file in publication.files %}
                                    <a class="dropdown-item"
                                       href="{{ file.file.url }}"><img
                                            src="https://maxcdn.icons8.com/Color/PNG/48/Very_Basic/file-48.png"
                                            title="File" height="32">{{ file.description }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon">Export as</span>
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-secondary dropdown-toggle"
                                data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            Citation format
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item"
                               href="{% url 'publications_bootstrap:id' publication.pk %}?ris">
                                RIS</a>
                            <a class="dropdown-item"
                               href="{% url 'publications_bootstrap:id' publication.pk %}?bibtex">
                                BibTex</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <abbr class="unapi-id" title="{{ publication.id }}"></abbr>
    <span class="Z3988" title="{{ publication.z3988 }}"></span>
</div>

publications_bootstrap/templates/publications_bootstrap/components/publications.html
{% for publication in publications %}
    {% include "publications_bootstrap/components/publication.html" %}
{% endfor %}

publications_bootstrap/templates/publications_bootstrap/components/publications_with_thumbnails.html
{% load static i18n %}
<ul class="list-unstyled">
    {% for publication in publications %}
        <li class="media">
            {% if publication.thumbnail %}
                <a href="{% if publication.code %}{{ publication.code }}{% else %}
                    {% url 'publications_bootstrap:id' publication.pk %}{% endif %}">
                    <img class="d-flex mr-3" src="{{ publication.thumbnail.url }}"/></a>
            {% endif %}
            <div class="media-body">
                {% include "publications_bootstrap/components/publication.html" %}
            </div>
        </li>
    {% endfor %}
</ul>

publications_bootstrap/templates/publications_bootstrap/components/section.html
<section class="publications">
    <h1 class="display-4">{{ title|capfirst|default:"Publications" }}</h1>
    <hr>
    {% for publication in publications %}
        {% include "publications_bootstrap/components/publication.html" %}
    {% endfor %}
</section>