publications_bootstrap/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

app_name = 'publications_bootstrap'
urlpatterns = [
    url(r'^$', views.by_year, name='index'),
    url(r'^(?P<publication_id>\d+)/$', views.by_id, name='id'),
    url(r'^year/(?P<year>\d+)/$', views.by_year, name='year'),
    url(r'^tag/(?P<tag>.+)/$', views.by_tag, name='tag'),
    url(r'^catalog/(?P<title>.+)/$', views.for_catalog, name='catalog'),
    url(r'^unapi/$', views.by_unapi, name='unapi'),
    url(r'^(?P<name>.+)/$', views.by_author, name='author'),
]

publications_bootstrap/templates/publications_bootstrap/base.html
{% extends "base.html" %}
{% load static %}

{% block pubo_head %}
    <link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications_bootstrap:unapi' %}" />
    {% block pubo_head_page %}
        {# Page specific head tags #}
    {% endblock pubo_head_page %}
{% endblock pubo_head %}

{% block pubo_css %}
    {% block pubo_css_page %}
        {# Page specific CSS #}
    {% endblock pubo_css_page %}
{% endblock pubo_css %}

{% block content %}
    <div class="pubo">
        {% if publication or publications %}
            {% include 'publications_bootstrap/components/download_all.html' %}
            {% block pubo_content_page %}
                {% include 'publications_bootstrap/components/section.html' %}
            {% endblock pubo_content_page %}
        {% else %}
            {% include 'publications_bootstrap/components/empty.html' %}
        {% endif %}
    </div>
{% endblock content %}

{% block pubo_js %}
    {% block pubo_js_page %}
        {# Page specific JS #}
    {% endblock pubo_js_page %}
{% endblock pubo_js %}